# Generated by Django 2.2.4 on 2019-10-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='student_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='NIL', max_length=10000),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_contact',
            field=models.CharField(default='NIL', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_email',
            field=models.EmailField(default='NIL', max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_contact',
            field=models.CharField(default='NIL', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_email',
            field=models.EmailField(default='NIL', max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_contact',
            field=models.CharField(default='NIL', max_length=10),
        ),
    ]
