# Generated by Django 2.2.4 on 2019-10-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20191015_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='father_email',
            field=models.EmailField(default='NIL', max_length=255, unique=True, verbose_name='Father email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_email',
            field=models.EmailField(default='NIL', max_length=255, unique=True, verbose_name='Mother email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_email',
            field=models.EmailField(default='NIL', max_length=255, unique=True, verbose_name='Student email'),
        ),
    ]
