# Generated by Django 2.2.4 on 2019-10-19 11:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('details', '0005_scores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scores',
            new_name='score',
        ),
    ]
