# Generated by Django 2.2.4 on 2019-10-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20191019_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.CharField(default='NIL', max_length=30),
        ),
    ]
